In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import os
import time

In [2]:
Pdata= pd.read_csv('click_data.csv')

In [3]:
Pdata

day                                userID  slots                k1  \
0       1  08bade48-1081-488f-b459-6c75d75312ae      2  2affa525151b6c51   
1      29  08bade48-1081-488f-b459-6c75d75312ae      3  769ed4a87b5010f4   
2      29  08bade48-1081-488f-b459-6c75d75312ae      2  769ed4a87b5010f4   
3      11  08bade48-1081-488f-b459-6c75d75312ae      1  769ed4a87b5010f4   
4      76  08bade48-1081-488f-b459-6c75d75312ae      2  769ed4a87b5010f4   
5      48  08bade48-1081-488f-b459-6c75d75312ae      3  2affa525151b6c51   
6      97  08bade48-1081-488f-b459-6c75d75312ae      2  2affa525151b6c51   
7     123  08bade48-1081-488f-b459-6c75d75312ae      5  769ed4a87b5010f4   
8     119  08bade48-1081-488f-b459-6c75d75312ae      3  2affa525151b6c51   
9      73  08bade48-1081-488f-b459-6c75d75312ae      1  2affa525151b6c51   
10     78  08bade48-1081-488f-b459-6c75d75312ae      2  769ed4a87b5010f4   
11     17  08bade48-1081-488f-b459-6c75d75312ae      2  769ed4a87b5010f4   
12     50  08bade48-1081-488f-b459-6c75d75312ae      2  2affa525151b6c51   
13      2  08bade48-1081-488f-b459-6c75d75312ae      9  769ed4a87b5010f4   
14     68  08bade48-1081-488f-b459-6c75d75312ae      3  2affa525151b6c51   
15     28  08bade48-1081-488f-b459-6c75d75312ae      4  2affa525151b6c51   
16     46  08bade48-1081-488f-b459-6c75d75312ae      3  2affa525151b6c51   
17     35  08bade48-1081-488f-b459-6c75d75312ae      2  769ed4a87b5010f4   
18     59  08bade48-1081-488f-b459-6c75d75312ae      2  2affa525151b6c51   
19     28  08bade48-1081-488f-b459-6c75d75312ae      3  2affa525151b6c51   
20     50  08bade48-1081-488f-b459-6c75d75312ae      5  2affa525151b6c51   
21     11  08bade48-1081-488f-b459-6c75d75312ae      2  769ed4a87b5010f4   
22     18  08bade48-1081-488f-b459-6c75d75312ae      4  2affa525151b6c51   
23     61  08bade48-1081-488f-b459-6c75d75312ae      3  2affa525151b6c51   
24     73  08bade48-1081-488f-b459-6c75d75312ae      5  2affa525151b6c51   
25     97  08bade48-1081-488f-b459-6c75d75312ae      5  2affa525151b6c51   
26     46  08bade48-1081-488f-b459-6c75d75312ae      4  2affa525151b6c51   
27    113  08bade48-1081-488f-b459-6c75d75312ae      2  769ed4a87b5010f4   
28     73  08bade48-1081-488f-b459-6c75d75312ae      2  2affa525151b6c51   
29     65  08bade48-1081-488f-b459-6c75d75312ae      4  2affa525151b6c51   
...   ...                                   ...    ...               ...   
8209  116  3a100534-7b8b-4536-9e35-73b4ae6b2a59      1  4389c8989b238f8e   
8210   89  3a100534-7b8b-4536-9e35-73b4ae6b2a59      2  4389c8989b238f8e   
8211  122  3a100534-7b8b-4536-9e35-73b4ae6b2a59      3  4389c8989b238f8e   
8212  114  3a100534-7b8b-4536-9e35-73b4ae6b2a59      1  4389c8989b238f8e   
8213  109  3a100534-7b8b-4536-9e35-73b4ae6b2a59      1  4389c8989b238f8e   
8214  108  9eb5a22f-1870-42b1-aaae-2faa5235ae34      1  aef4ee042bea9c6b   
8215  108  9eb5a22f-1870-42b1-aaae-2faa5235ae34      3  aef4ee042bea9c6b   
8216   74  3a100534-7b8b-4536-9e35-73b4ae6b2a59     11  4389c8989b238f8e   
8217  107  3a100534-7b8b-4536-9e35-73b4ae6b2a59      2  4389c8989b238f8e   
8218  104  3a100534-7b8b-4536-9e35-73b4ae6b2a59      4  4389c8989b238f8e   
8219  108  3a100534-7b8b-4536-9e35-73b4ae6b2a59      4  4389c8989b238f8e   
8220  100  3a100534-7b8b-4536-9e35-73b4ae6b2a59      2  4389c8989b238f8e   
8221   99  3a100534-7b8b-4536-9e35-73b4ae6b2a59      4  4389c8989b238f8e   
8222   97  3a100534-7b8b-4536-9e35-73b4ae6b2a59      1  4389c8989b238f8e   
8223   94  3a100534-7b8b-4536-9e35-73b4ae6b2a59      2  4389c8989b238f8e   
8224   97  3a100534-7b8b-4536-9e35-73b4ae6b2a59      3  4389c8989b238f8e   
8225   90  3a100534-7b8b-4536-9e35-73b4ae6b2a59      1  4389c8989b238f8e   
8226   91  3a100534-7b8b-4536-9e35-73b4ae6b2a59      1  4389c8989b238f8e   
8227   87  3a100534-7b8b-4536-9e35-73b4ae6b2a59      3  4389c8989b238f8e   
8228   92  3a100534-7b8b-4536-9e35-73b4ae6b2a59      2  4389c8989b238f8e   
8229   78  3a100534-7b8b-4536-9e35-73b4ae6b2a59      4

In [4]:
Pdata['userID'].value_counts()

3a100534-7b8b-4536-9e35-73b4ae6b2a59    3750
670f01e0-e665-4126-97f7-25583ad38a80    2133
bcbad0a2-c502-44ba-9e8a-16ade955ece5     698
b5f02143-b63e-4062-bb82-0624909e55ac     489
9eb5a22f-1870-42b1-aaae-2faa5235ae34     254
16f17cbd-0dd3-4785-ba48-b249eab8c032     137
44b9f088-7d6e-48c9-91a9-ab0fca5cdeeb     109
52852966-92dd-43ac-8435-01b9e6021c7c      76
2aa7a8f8-03dc-4ba8-a149-18e22fea1de0      68
08bade48-1081-488f-b459-6c75d75312ae      60
2e405ca2-8810-4448-b682-5d186ab24391      54
c3ad7094-88ae-4a82-a9e1-00bf7acf29e2      49
fa7f5e1c-3016-450a-a778-6aaca9ba1d4a      47
93a72bf6-386f-4f09-855a-762ab0745cb8      47
b5bdf235-9c77-4559-a4da-3e1ec94f9e92      42
90546bf0-1794-4282-a2b1-81dca290800b      40
9d3fa57e-444f-421f-9c72-ca655aa75e30      38
28f05d7e-5c30-4b27-9f81-d88d20d08ac6      38
2979fdb3-a108-434c-9547-940c37e671f0      37
c536f9aa-9f3a-43e1-832e-9434911aa3b3      29
14786232-228b-4215-914c-b1bf75098278      10
0e572b2d-4b06-4e93-9244-28d3cbe1d53e       9
a5002d6d-3

In [5]:
Pdata['userID'].unique()

array(['08bade48-1081-488f-b459-6c75d75312ae',
       'a5002d6d-3056-4c89-bd2e-f3fa51cb8422',
       'b5f02143-b63e-4062-bb82-0624909e55ac',
       'bcbad0a2-c502-44ba-9e8a-16ade955ece5',
       '10fa3930-fa02-4c4a-8fd6-4bc5d831c171',
       'c536f9aa-9f3a-43e1-832e-9434911aa3b3',
       '670f01e0-e665-4126-97f7-25583ad38a80',
       '2aa7a8f8-03dc-4ba8-a149-18e22fea1de0',
       '14786232-228b-4215-914c-b1bf75098278',
       '9d3fa57e-444f-421f-9c72-ca655aa75e30',
       '28f05d7e-5c30-4b27-9f81-d88d20d08ac6',
       '2e405ca2-8810-4448-b682-5d186ab24391',
       'c3ad7094-88ae-4a82-a9e1-00bf7acf29e2',
       '0e572b2d-4b06-4e93-9244-28d3cbe1d53e',
       '90546bf0-1794-4282-a2b1-81dca290800b',
       '44b9f088-7d6e-48c9-91a9-ab0fca5cdeeb',
       'fa7f5e1c-3016-450a-a778-6aaca9ba1d4a',
       'f583da53-bff4-436e-8e87-487f8122beee',
       '3a100534-7b8b-4536-9e35-73b4ae6b2a59',
       '001097ea-d0b7-491c-9146-debb2ac212d7',
       '52852966-92dd-43ac-8435-01b9e6021c7c',
       '2979f

In [11]:
len(Data)

8239

In [8]:
UserID=np.array(Pdata['userID'].unique())

In [9]:
len(UserID)

28

In [10]:
Data=np.array(Pdata)

In [45]:
Data[8238]

array([78, 18, 1, 16111, 42437, 9361, 32816, 12331, 300.0, 172, 20],
      dtype=object)

In [40]:
for i in range(len(Data)):
    for j in range(len(UserID)):
        if Data[i][1]==UserID[j]:
            Data[i][1]=j
            break

In [13]:
Data

array([[1, 0, 2, ..., 100.0, 2, 0],
       [29, 0, 3, ..., 100.0, 1, 0],
       [29, 0, 2, ..., 100.0, 1, 0],
       ...,
       [114, 18, 4, ..., 630.0, 50, 8],
       [79, 18, 1, ..., 300.0, 82, 11],
       [78, 18, 1, ..., 300.0, 172, 20]], dtype=object)

In [26]:
Pkey= pd.read_csv('keywordID.csv', dtype='str')

In [27]:
KeywordID=np.array(Pkey)

In [34]:
len(KeywordID)

75358

In [33]:
start = time.clock()
for i in range(len(Data)):
    for j in range(len(KeywordID)):
        for k in range(5):
            if Data[i][3+k]==KeywordID[j]:
                Data[i][3+k]=j
                break
                
print("time is:",(time.clock() - start))

C:\Users\zhaoq\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: time.clock has been deprecated in Python 3.3 and will be removed from Python 3.8: use time.perf_counter or time.process_time instead
  """Entry point for launching an IPython kernel.


time is: 10130.503377971


C:\Users\zhaoq\Anaconda3\lib\site-packages\ipykernel_launcher.py:9: DeprecationWarning: time.clock has been deprecated in Python 3.3 and will be removed from Python 3.8: use time.perf_counter or time.process_time instead
  if __name__ == '__main__':


In [43]:
np.savetxt("clickProcessed.csv", Data,fmt='%5s',delimiter=",")

In [12]:
ddata= pd.read_csv('clickProcessed.csv')
Data=np.array(ddata,dtype='double')

In [13]:
# for i in range(len(KeywordID)):
#     if KeywordID[i]=='c242db3e662da86f':
#         print(i)

In [14]:
Quality=np.zeros((len(UserID),3))
CTR=np.zeros((10,3))

In [15]:
Data[0][9]

2.0

In [16]:
for i in range(len(Data)):
    Quality[int(Data[i][1])][0]+=Data[i][9]
    Quality[int(Data[i][1])][1]+=Data[i][10]
    if Data[i][2]<=10:
        CTR[int(Data[i][2]-1)][0]+=Data[i][9]
        CTR[int(Data[i][2]-1)][1]+=Data[i][10]

In [17]:
for i in range(len(CTR)):
    CTR[i][2]=((CTR[i][1])/CTR[i][0])

In [18]:
CTR

array([[4.23600000e+03, 2.40000000e+02, 5.66572238e-02],
       [3.54900000e+03, 1.08000000e+02, 3.04311074e-02],
       [4.49200000e+03, 9.30000000e+01, 2.07034728e-02],
       [4.83500000e+03, 8.10000000e+01, 1.67528438e-02],
       [3.68600000e+03, 5.00000000e+01, 1.35648399e-02],
       [2.49100000e+03, 2.40000000e+01, 9.63468487e-03],
       [2.20400000e+03, 3.00000000e+01, 1.36116152e-02],
       [1.84000000e+03, 2.00000000e+01, 1.08695652e-02],
       [1.33800000e+03, 2.00000000e+01, 1.49476831e-02],
       [1.24900000e+03, 1.30000000e+01, 1.04083267e-02]])

In [19]:
for i in range(len(Quality)):
    Quality[i][2]=((Quality[i][1])/Quality[i][0])

In [20]:
Quality

array([[7.80000000e+01, 0.00000000e+00, 0.00000000e+00],
       [1.40000000e+01, 0.00000000e+00, 0.00000000e+00],
       [1.03400000e+03, 1.00000000e+00, 9.67117988e-04],
       [1.27600000e+03, 1.00000000e+00, 7.83699060e-04],
       [3.60000000e+01, 0.00000000e+00, 0.00000000e+00],
       [8.00000000e+01, 0.00000000e+00, 0.00000000e+00],
       [4.45800000e+03, 7.30000000e+01, 1.63750561e-02],
       [1.22000000e+02, 1.50000000e+01, 1.22950820e-01],
       [1.20000000e+01, 0.00000000e+00, 0.00000000e+00],
       [6.00000000e+01, 1.00000000e+00, 1.66666667e-02],
       [6.00000000e+01, 0.00000000e+00, 0.00000000e+00],
       [7.80000000e+01, 5.00000000e+00, 6.41025641e-02],
       [9.10000000e+01, 0.00000000e+00, 0.00000000e+00],
       [1.10000000e+01, 0.00000000e+00, 0.00000000e+00],
       [7.90000000e+01, 2.00000000e+00, 2.53164557e-02],
       [1.53000000e+02, 6.00000000e+00, 3.92156863e-02],
       [1.97000000e+02, 1.00000000e+01, 5.07614213e-02],
       [4.00000000e+00, 0.00000

In [21]:
for i in range(len(Quality)):
    if Quality[i][2]==0:
        Quality[i][2]=0.01

In [22]:
for i in range(len(Data)):
    key_list=[]
    for j in range(5):
        key_list.append(Data[i][3+j])
    key_list.sort()
    for j in range(5):
        Data[i][3+j]=key_list[j]

In [29]:
key_Frequency=np.zeros(len(KeywordID))
for i in range(len(Data)):
    for j in range(5):
        if Data[i][3+j]!=7470000000000000:
            key_Frequency[int(Data[i][3+j])]+=1

In [30]:
KAT=[]
for i in range(len(key_Frequency)):
    if key_Frequency[i]!=0:
        abc=[]
        abc.append(i)
        abc.append(key_Frequency[i])
        KAT.append(abc)

In [31]:
KAT=np.array(KAT,dtype='int')
KAT_S = np.argsort(KAT[:,1])
KAT_S=KAT[KAT_S]

In [32]:
KAT_S

array([[39318,     1],
       [69036,     1],
       [31390,     1],
       ...,
       [42437,  1627],
       [59542,  1826],
       [32816,  4034]])

In [33]:
for i in range(len(KAT_S)-1,len(KAT_S)-11,-1):
    print("Keyword ID:",KAT_S[i][0],", Appear times:",KAT_S[i][1])

Keyword ID: 32816 , Appear times: 4034
Keyword ID: 59542 , Appear times: 1826
Keyword ID: 42437 , Appear times: 1627
Keyword ID: 27680 , Appear times: 1583
Keyword ID: 69125 , Appear times: 1426
Keyword ID: 53990 , Appear times: 1185
Keyword ID: 9361 , Appear times: 1147
Keyword ID: 12331 , Appear times: 1147
Keyword ID: 16111 , Appear times: 1147
Keyword ID: 49935 , Appear times: 992


In [34]:
bidder_List=[]

In [35]:
for i in range(len(Data)):
    if Data[i][3]==KAT_S[-1][0] or Data[i][4]==KAT_S[-1][0] or Data[i][5]==KAT_S[-1][0] or Data[i][6]==KAT_S[-1][0] or Data[i][7]==KAT_S[-1][0]:
        bidder_List.append(Data[i])

In [36]:
Bid=np.zeros((len(bidder_List),2))

In [37]:
for i in range(len(bidder_List)):
    Bid[i][0]=bidder_List[i][1]
    Bid[i][1]=bidder_List[i][8]

In [38]:
Bid=np.array(Bid, dtype='int')

In [39]:
uniquesBid = np.unique(Bid,axis=0)

In [40]:
for i in range(len(uniquesBid)-1,0,-1):
    if uniquesBid[i][1]>= uniquesBid[i-1][1] and uniquesBid[i][0]==uniquesBid[i-1][0]:
        uniquesBid[i-1][1]=uniquesBid[i][1]

In [41]:
uniquesBid = np.unique(uniquesBid,axis=0)

In [42]:
uniquesBid

array([[   0,  100],
       [   6,  500],
       [  11,  500],
       [  17,  410],
       [  18,  630],
       [  19, 1250],
       [  24, 1010]])

In [43]:
b_order = np.argsort(uniquesBid[:,1])

In [44]:
OrderBid=uniquesBid[b_order]

In [45]:
OrderBid

array([[   0,  100],
       [  17,  410],
       [   6,  500],
       [  11,  500],
       [  18,  630],
       [  24, 1010],
       [  19, 1250]])

In [142]:
class Slot:
    CTR=-1
    Owner=-1
    Cost=0
    
    def __init__(self, Ctr):
        self.CTR=Ctr

In [143]:
class Bid:
    bid=-1
    bidder=-1
    quality=1
    
    def __init__(self, Bidder,Bid,qua):
        self.bid=Bid
        self.bidder=Bidder
        self.quality=qua[int(self.bidder)]

In [144]:
class Auction:
    KeywordID=-1
    bids=[]
    quality=[]
    
    def __init__(self,K_ID,bid,qua):
        self.KeywordID = K_ID
        for i in range(len(bid)):
            self.bids.append(bid[i])
        quality=qua
    
    def VCG(self,slots):
        length = len(slots)
        
        for i in range(len(slots)):
            sum=0
            
            for j in range(i+1,len(slots)+1):
                if j!=(len(slots)):
                    sum+=self.bids[j].bid*(slots[j-1].CTR - slots[j].CTR)
                else:
                    sum+=self.bids[j].bid*(slots[j-1].CTR - 0)
                    
            slots[i].Cost=sum*(1/slots[i].CTR)
        
        for i in range(0, length):
            slots[i].Owner = self.bids[i].bidder
    
    def GSP(self,slots):
        length = len(slots)
        
        for i in range(len(self.bids)):
            for j in range(i+1,len(self.bids)):
                if (self.bids[i].bid*self.bids[i].quality)<(self.bids[j].bid*self.bids[j].quality):
                    temp=self.bids[i]
                    self.bids[i]=self.bids[j]
                    self.bids[j]=temp
        
#         for i in range(len(self.bids)):
#             print("BidderID:",self.bids[i].bidder)
#             print("Bid:",self.bids[i].bid)
#             print("Mark:",self.bids[i].bid*self.bids[i].quality)

        
        for i in range(length):
            slots[i].Cost =(self.bids[i+1].bid*self.bids[i+1].quality)/self.bids[i].quality
#             slots[i].Cost =self.bids[i+1].bid
            
        for i in range(0, length):
            slots[i].Owner = self.bids[i].bidder
            
    def GFP(self,slots):
        length=len(slots)
        
        for i in range(length):
            slots[i].Cost=self.bids[i].bid
        
        for i in range(length):
            slots[i].Owner = self.bids[i].bidder

In [145]:
qua=Quality[:,2].tolist()
bid=[]
for i in range(len(OrderBid)-1,-1,-1):
    bbb=Bid(OrderBid[i][0],OrderBid[i][1],qua)
    bid.append(bbb)

slots=[]
for i in range(4):
    sss=Slot(CTR[i][2])
    slots.append(sss)

In [146]:
for i,slot in enumerate(slots):
    print("Slot",i+1,"'s CTR is ",slots[i].CTR)

Slot 1 's CTR is  0.056657223796033995
Slot 2 's CTR is  0.030431107354184278
Slot 3 's CTR is  0.02070347284060552
Slot 4 's CTR is  0.016752843846949327


In [147]:
for i in range(len(bid)):
    print("Bidder ID:%2d, Bid: %6.2f"% (bid[i].bidder,bid[i].bid))

Bidder ID:19, Bid: 1250.00
Bidder ID:24, Bid: 1010.00
Bidder ID:18, Bid: 630.00
Bidder ID:11, Bid: 500.00
Bidder ID: 6, Bid: 500.00
Bidder ID:17, Bid: 410.00
Bidder ID: 0, Bid: 100.00


In [148]:
BIDDD=np.zeros(28)
for i in range(len(bid)):
    BIDDD[int(bid[i].bidder)]=bid[i].bid

In [130]:
auction = Auction(KAT_S[-1][0], bid,qua)
auction.VCG(slots)

In [132]:
print(" %12s   %8s    %8s    %8s\n" % ("CTR", "Cost (per click)", "Bidder ID","Expected Utility"))
for i,slot in enumerate(slots):
    print("slot %d:  %5.3f    %8.2f            %d          %8.2f" % (i+1, float(slot.CTR), float(slot.Cost), slot.Owner,slot.CTR*(BIDDD[int(slot.Owner)]-slot.Cost)))
revenue=0
for i in range(len(slots)):
    revenue+=slots[i].Cost*slots[i].CTR*100*qua[slots[i].Owner]
Welfare=0
for i in range(len(slots)):
    Welfare=Welfare+qua[int(slots[i].Owner)]*BIDDD[int(slots[i].Owner)]
print()
print("Social Welfare is: %.2f."%Welfare)
print("Revenue is:       %.2f.          (100 views)"%revenue) 


          CTR   Cost (per click)    Bidder ID    Expected Utility

slot 1:  0.057      758.39            19             27.85
slot 2:  0.030      541.56            24             14.26
slot 3:  0.021      500.00            18              2.69
slot 4:  0.017      500.00            11              0.00

Social Welfare is: 69.59.
Revenue is:       137.69.          (100 views)


In [149]:
auctionGSP = Auction(KAT_S[-1][0], bid,qua)
auctionGSP.GSP(slots)

In [150]:
print(" %12s   %8s    %8s    %8s\n" % ("CTR", "Cost (per click)", "Bidder ID","Expected Utility"))
for i,slot in enumerate(slots):
    print("slot %d:  %5.3f    %8.2f            %d          %8.2f" % (i+1, float(slot.CTR), float(slot.Cost), slot.Owner,slot.CTR*(BIDDD[int(slot.Owner)]-slot.Cost)))
revenue=0
for i in range(len(slots)):
    revenue+=slots[i].Cost*slots[i].CTR*100*qua[slots[i].Owner]
Welfare=0
for i in range(len(slots)):
    Welfare=Welfare+qua[int(slots[i].Owner)]*BIDDD[int(slots[i].Owner)]
print()
print("Social Welfare is: %.2f."%Welfare)
print("Revenue is:       %.2f.          (100 views)"%revenue) 

          CTR   Cost (per click)    Bidder ID    Expected Utility

slot 1:  0.057      233.02            11             15.13
slot 2:  0.030      527.21            18              3.13
slot 3:  0.021     1010.00            19              4.97
slot 4:  0.017      818.75            24              3.20

Social Welfare is: 69.59.
Revenue is:       157.30.          (100 views)


In [140]:
auctionGFP = Auction(KAT_S[-1][0], bid,qua)
auctionGFP.GFP(slots)

In [141]:
print(" %12s   %8s    %8s    %8s\n" % ("CTR", "Cost (per click)", "Bidder ID","Expected Utility"))
for i,slot in enumerate(slots):
    print("slot %d:  %5.3f    %8.2f            %d          %8.2f" % (i+1, float(slot.CTR), float(slot.Cost), slot.Owner,slot.CTR*(BIDDD[int(slot.Owner)]-slot.Cost)))
revenue=0
for i in range(len(slots)):
    revenue+=slots[i].Cost*slots[i].CTR*100*qua[slots[i].Owner]
Welfare=0
for i in range(len(slots)):
    Welfare=Welfare+qua[int(slots[i].Owner)]*BIDDD[int(slots[i].Owner)]
print()
print("Social Welfare is: %.2f."%Welfare)
print("Revenue is:       %.2f.          (100 views)"%revenue) 

          CTR   Cost (per click)    Bidder ID    Expected Utility

slot 1:  0.057     1250.00            19              0.00
slot 2:  0.030     1010.00            24              0.00
slot 3:  0.021      630.00            18              0.00
slot 4:  0.017      500.00            11              0.00

Social Welfare is: 69.59.
Revenue is:       186.18.          (100 views)
